#---------- Lets use an "Anchor" and Aliases "&" 
# to reduce codes (circleci/node:13.8.0) repetition
# Note: (anchors & Aliases can only be created once in your code like here)
defaults: &defaults
  # use the the Docker Executor
  docker:
    # Use a light weight image | we can use
      - image: circleci/node:13.8.0
  working_directory: ~/project
      
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

#----------- How to use Commands (for Reusable code & reduce code repetition)?
# Commands are similar to functions & can be created multiple times.
commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

# Second way/Option for creating command  to Pass Circle_workflow_id as parameter 
# in our  commands instead of Enviromental variable
commands:
  print_pipeline_id_2:
    parameters:
      id:
        type: string
    steps:
      - run: echo << parameters.id >>
    # ----------- Jobs Section -------------------------#
jobs:
  # -----------------First Job ---------------
  print_hello:
    # Let's use the "defaults" alias above to reduce  repeat codes for docker images  
    <<: *defaults
    # a step that runs a simple Bash command
    steps:
      - run: echo hello 
  
  #------------------- My Second-job ---------------
  print_srename:
    # Now we just use the default alias and having less repeat codes  
    <<: *defaults
    steps:
      - run: echo jldroid25 

  # ----------Job to Print Env Variable's Key (not its value) once job runs
  print_env_var:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout 
      - run:
          name: "echo an ENV var in pipeline project-setup section"
          command: | 
            echo $VIZGEN_DEVOPSRENGINEER_NAME

  #--------------------- A Job for Sharing a File between two jobs ------------
  engineer_job_postion_title:
    <<: *defaults
    steps:
    # save the data to this file/create if not exist
      - run: echo "Site Reliability Engineer" > ~/output.txt

      # persist_to_workspace: Special step used to persist a temporary file to be used 
      # by another job in the workflow.
      - persist_to_workspace:

        # Root: (Required), Either an absolute path or a path relative to working_directory
          root: ~/

          # Path: (Required), Glob identifying file(s), or a non-glob path to a directory to 
          # add to the shared workspace. 
          # Interpreted as relative to the workspace root. 
          # Must not be the workspace root itself.
          paths:
            - output.txt 
  # Job to print the file data
  print_output_file:
    <<: *defaults
    steps:
      # similar to attaching a hard drive.
      #Attach_workspace: (required), Special step used to attach the workflow’s workspace to the current container. 
      # The full contents of the workspace are downloaded and copied into the directory 
      # the workspace is being attached at
      - attach_workspace:

        # at: (required), Directory to attach the workspace to.
          at: ~/
        # Bash command to Print the content 
      - run: cat ~/output.txt
  
  # Jobs to print Pipeline_id
  sredevops_pip_id:
    <<: *defaults
    steps:
      - print_pipeline_id

    # Jobs to print Pipeline_id 2nd way as a parameter
    sredevops_pip_id_2:
      <<: *defaults
      steps:
        - print_pipeline_id_2:
            id: << pipeline.id >>

# ---------------- Workflow section ----------
workflows:
  # Name of the workflow "DevOps-SRE-WF"
   DevOps-Sre-WF:

    jobs:
    # Run the print_hello  
      - print_hello

    # Run print_srename
      - print_srename:
        # Use the requires key to make your print_srename wait
        # for the print_hello job to finish.
          requires:
            - print_hello

    # Running the ENV Var job
      - print_env_var 

    # Run the  engineer_job_postion_title's job
      - engineer_job_postion_title
      - print_output_file:
          requires:
            - engineer_job_postion_title
    # Run sredevops_pip_id
      - sredevops_pip_id
